CREATE DATABASE transcation;
USE transcation;

CREATE TABLE transactions (
    transaction_id INT PRIMARY KEY,
    customer_id INT,
    region VARCHAR(20),
    transaction_date DATE,
    amount INT);

INSERT INTO transactions VALUES
(1,101,'North','2024-01-05',500),
(2,102,'South','2024-01-06',300),
(3,101,'North','2024-01-10',700),
(4,103,'East','2024-01-15',200),
(5,104,'West','2024-01-20',900),
(6,102,'South','2024-01-25',400),
(7,101,'North','2024-02-02',600),
(8,103,'East','2024-02-05',300),
(9,105,'North','2024-02-10',1000),
(10,104,'West','2024-02-15',500);


-- What is the total revenue generated by the company?
SELECT SUM(amount) AS total_revenue
FROM transactions;

-- What is the average transaction value?
SELECT AVG(amount) AS avg_transaction_value
FROM transactions;

-- Show total revenue and number of transactions per month
SELECT DATE_FORMAT(transaction_date ,'%Y-%m') AS month,
SUM(amount) AS total_revenue , 
COUNT(transaction_id) AS transaction_count
FROM transactions 
GROUP BY month;

-- Which transactions contributed more than the average transaction amount?
SELECT transaction_id , amount
FROM transactions 
WHERE amount > (SELECT AVG(amount) 
				FROM transactions);
                
                
-- How many unique customers made purchases?
SELECT COUNT(DISTINCT(customer_id)) AS unique_customers
FROM transactions;

-- Show total spending per customer
SELECT customer_id , SUM(amount) AS total_spent
FROM transactions 
GROUP BY customer_id;

-- Which customers made more than 2 transactions?
SELECT customer_id , COUNT(transaction_id) AS transaction_count
FROM transactions
GROUP BY customer_id
HAVING transaction_count > 2;

-- Find customers whose total spending is above the company average customer spending
WITH customers_spending AS (
SELECT customer_id, SUM(amount) AS total_spent
FROM transactions 
GROUP BY customer_id)
SELECT c.customer_id, c.total_spent
FROM customers_spending c
WHERE c.total_spent > (SELECT AVG(total_spent) FROM customers_spending);

-- Show total revenue by region
SELECT region , SUM(amount) AS revenue
FROM transactions
GROUP BY region
ORDER BY revenue DESC;

-- Show average transaction value by region
SELECT region , AVG(amount) AS avg_revenue
FROM transactions
GROUP BY region
ORDER BY avg_revenue DESC;

-- Which region has the highest number of transactions?
SELECT region , COUNT(transaction_id) AS transaction_count 
FROM transactions 
GROUP BY region
ORDER BY transaction_count DESC
LIMIT 1;

-- Which regions generated more than 25% of total revenue?
WITH regionalrevenue AS (
SELECT region, SUM(amount) AS regional_revenue 
FROM transactions 
GROUP BY region)

SELECT region, regional_revenue
FROM regionalrevenue
WHERE (regional_revenue * 100) / (SELECT SUM(amount) FROM transactions) > 25.0;

-- Show revenue contribution (%) by region
WITH revenue_contribution AS(
SELECT region , SUM(amount) As regional_revenue
FROM transactions
GROUP BY region)

SELECT region , regional_revenue ,
ROUND((regional_revenue*100)/(SELECT SUM(amount) FROM transactions),2) AS revenue_percentage
FROM revenue_contribution
ORDER BY revenue_percentage DESC;

-- Identify high-value customers (customers whose average transaction value > 600)
SELECT customer_id , AVG(amount) AS avg_transaction_value
FROM transactions
GROUP BY customer_id
HAVING avg_transaction_value > 600;

-- Find regions where total revenue is below the overall average regional revenue
SELECT region , SUM(amount) AS revenue 
FROM transactions
GROUP BY region
HAVING revenue < (SELECT SUM(amount) / COUNT(DISTINCT region) 
				  FROM transactions);
			
-- or --
WITH RegionalTotals AS (
    SELECT region, SUM(amount) AS revenue
    FROM transactions
    GROUP BY region)
    
SELECT region, revenue
FROM RegionalTotals
WHERE revenue < (SELECT AVG(revenue) FROM RegionalTotals);
